# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rulrich/work/Documents/proposals/ERC_Consolidator/musim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/work/Documents/proposals/ERC_Consolidator/musim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/work/Documents/proposals/ERC_Consolidator/musim/CMakeFiles /home/work/Documents/proposals/ERC_Consolidator/musim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/work/Documents/proposals/ERC_Consolidator/musim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named musim

# Build rule for target.
musim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 musim
.PHONY : musim

# fast build rule for target.
musim/fast:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/build
.PHONY : musim/fast

# Manual pre-install relink rule for target.
musim/preinstall:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/preinstall
.PHONY : musim/preinstall

musim.o: musim.cc.o

.PHONY : musim.o

# target to build an object file
musim.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/musim.cc.o
.PHONY : musim.cc.o

musim.i: musim.cc.i

.PHONY : musim.i

# target to preprocess a source file
musim.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/musim.cc.i
.PHONY : musim.cc.i

musim.s: musim.cc.s

.PHONY : musim.s

# target to generate assembly for a file
musim.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/musim.cc.s
.PHONY : musim.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/DetectorConstructionDet.o: src/DetectorConstructionDet.cc.o

.PHONY : src/DetectorConstructionDet.o

# target to build an object file
src/DetectorConstructionDet.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorConstructionDet.cc.o
.PHONY : src/DetectorConstructionDet.cc.o

src/DetectorConstructionDet.i: src/DetectorConstructionDet.cc.i

.PHONY : src/DetectorConstructionDet.i

# target to preprocess a source file
src/DetectorConstructionDet.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorConstructionDet.cc.i
.PHONY : src/DetectorConstructionDet.cc.i

src/DetectorConstructionDet.s: src/DetectorConstructionDet.cc.s

.PHONY : src/DetectorConstructionDet.s

# target to generate assembly for a file
src/DetectorConstructionDet.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorConstructionDet.cc.s
.PHONY : src/DetectorConstructionDet.cc.s

src/DetectorHit.o: src/DetectorHit.cc.o

.PHONY : src/DetectorHit.o

# target to build an object file
src/DetectorHit.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorHit.cc.o
.PHONY : src/DetectorHit.cc.o

src/DetectorHit.i: src/DetectorHit.cc.i

.PHONY : src/DetectorHit.i

# target to preprocess a source file
src/DetectorHit.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorHit.cc.i
.PHONY : src/DetectorHit.cc.i

src/DetectorHit.s: src/DetectorHit.cc.s

.PHONY : src/DetectorHit.s

# target to generate assembly for a file
src/DetectorHit.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorHit.cc.s
.PHONY : src/DetectorHit.cc.s

src/DetectorSD.o: src/DetectorSD.cc.o

.PHONY : src/DetectorSD.o

# target to build an object file
src/DetectorSD.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorSD.cc.o
.PHONY : src/DetectorSD.cc.o

src/DetectorSD.i: src/DetectorSD.cc.i

.PHONY : src/DetectorSD.i

# target to preprocess a source file
src/DetectorSD.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorSD.cc.i
.PHONY : src/DetectorSD.cc.i

src/DetectorSD.s: src/DetectorSD.cc.s

.PHONY : src/DetectorSD.s

# target to generate assembly for a file
src/DetectorSD.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/DetectorSD.cc.s
.PHONY : src/DetectorSD.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/MCPMinus.o: src/MCPMinus.cc.o

.PHONY : src/MCPMinus.o

# target to build an object file
src/MCPMinus.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/MCPMinus.cc.o
.PHONY : src/MCPMinus.cc.o

src/MCPMinus.i: src/MCPMinus.cc.i

.PHONY : src/MCPMinus.i

# target to preprocess a source file
src/MCPMinus.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/MCPMinus.cc.i
.PHONY : src/MCPMinus.cc.i

src/MCPMinus.s: src/MCPMinus.cc.s

.PHONY : src/MCPMinus.s

# target to generate assembly for a file
src/MCPMinus.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/MCPMinus.cc.s
.PHONY : src/MCPMinus.cc.s

src/PMTHit.o: src/PMTHit.cc.o

.PHONY : src/PMTHit.o

# target to build an object file
src/PMTHit.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PMTHit.cc.o
.PHONY : src/PMTHit.cc.o

src/PMTHit.i: src/PMTHit.cc.i

.PHONY : src/PMTHit.i

# target to preprocess a source file
src/PMTHit.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PMTHit.cc.i
.PHONY : src/PMTHit.cc.i

src/PMTHit.s: src/PMTHit.cc.s

.PHONY : src/PMTHit.s

# target to generate assembly for a file
src/PMTHit.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PMTHit.cc.s
.PHONY : src/PMTHit.cc.s

src/PMTSD.o: src/PMTSD.cc.o

.PHONY : src/PMTSD.o

# target to build an object file
src/PMTSD.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PMTSD.cc.o
.PHONY : src/PMTSD.cc.o

src/PMTSD.i: src/PMTSD.cc.i

.PHONY : src/PMTSD.i

# target to preprocess a source file
src/PMTSD.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PMTSD.cc.i
.PHONY : src/PMTSD.cc.i

src/PMTSD.s: src/PMTSD.cc.s

.PHONY : src/PMTSD.s

# target to generate assembly for a file
src/PMTSD.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PMTSD.cc.s
.PHONY : src/PMTSD.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/StackingAction.o: src/StackingAction.cc.o

.PHONY : src/StackingAction.o

# target to build an object file
src/StackingAction.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/StackingAction.cc.o
.PHONY : src/StackingAction.cc.o

src/StackingAction.i: src/StackingAction.cc.i

.PHONY : src/StackingAction.i

# target to preprocess a source file
src/StackingAction.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/StackingAction.cc.i
.PHONY : src/StackingAction.cc.i

src/StackingAction.s: src/StackingAction.cc.s

.PHONY : src/StackingAction.s

# target to generate assembly for a file
src/StackingAction.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/StackingAction.cc.s
.PHONY : src/StackingAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/musim.dir/build.make CMakeFiles/musim.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... musim"
	@echo "... edit_cache"
	@echo "... musim.o"
	@echo "... musim.i"
	@echo "... musim.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/DetectorConstructionDet.o"
	@echo "... src/DetectorConstructionDet.i"
	@echo "... src/DetectorConstructionDet.s"
	@echo "... src/DetectorHit.o"
	@echo "... src/DetectorHit.i"
	@echo "... src/DetectorHit.s"
	@echo "... src/DetectorSD.o"
	@echo "... src/DetectorSD.i"
	@echo "... src/DetectorSD.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/MCPMinus.o"
	@echo "... src/MCPMinus.i"
	@echo "... src/MCPMinus.s"
	@echo "... src/PMTHit.o"
	@echo "... src/PMTHit.i"
	@echo "... src/PMTHit.s"
	@echo "... src/PMTSD.o"
	@echo "... src/PMTSD.i"
	@echo "... src/PMTSD.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/StackingAction.o"
	@echo "... src/StackingAction.i"
	@echo "... src/StackingAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

